# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    cruise_search:
        class: CruiseBundle\Service\CruiseSearch
        arguments: ['@doctrine','@memcache.default']

    cruise:
        class: CruiseBundle\Service\Cruise
        arguments: ['@doctrine']

    num2str:
        class: CruiseBundle\Service\NumToString

    app.twig_extension:
        class: CruiseBundle\Twig\AppExtension
        public: false
        tags:
            - { name: 'twig.extension' }