<?php

namespace BaseBundle\Repository;

/**
 * ShipCabinImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipCabinImageRepository extends \Doctrine\ORM\EntityRepository
{
}
